---
# Universal Deployment Playbook
# This playbook can be run from anywhere and auto-detects context
#
# Usage:
#   ansible-playbook deploy.yml
#   ansible-playbook deploy.yml -e "mcp_servers=['filesystem']" -e "gpu_enabled=true"
#
# The playbook automatically:
# - Detects the role location
# - Discovers MCP servers in standard locations
# - Uses sensible defaults that can be overridden with -e

- name: Deploy Ollama and mcphost with MCP servers
  hosts: localhost
  connection: local
  gather_facts: false
  become: true
  vars:
    role_files_path: "{{ playbook_dir }}/roles/ansible-ollama_mcphost"
    deployment_model: "{{ model | default('gpt-oss:20b') }}"
    deployment_gpu_enabled: "{{ gpu_enabled | default(false) | bool }}"
    deployment_gpu_runtime: "{{ gpu_runtime | default('rocm') }}"
    deployment_auto_discover: "{{ auto_discover | default(false) | bool }}"
    deployment_mcp_servers_raw: "{{ mcp_servers | default([]) }}"
    deployment_api_key: "{{ api_key | default('') }}"
    deployment_api_key_env_var: "{{ api_key_env_var | default('') }}"
    deployment_system_prompt: "{{ system_prompt | default('') }}"
    deployment_system_prompt_file: "{{ system_prompt_file | default('') }}"
  pre_tasks:
    - name: Normalize MCP server selection
      ansible.builtin.set_fact:
        deployment_mcp_servers: >-
          {% set raw = deployment_mcp_servers_raw %}
          {% if raw is string %}
            {% set trimmed = raw | trim %}
            {% if trimmed == '' %}
              []
            {% elif trimmed.startswith('[') %}
              {{ trimmed | from_yaml }}
            {% else %}
              {{ trimmed.split(',') | map('trim') | reject('equalto','') | list }}
            {% endif %}
          {% elif raw is sequence %}
            {{ raw | list }}
          {% else %}
            []
          {% endif %}

    - name: Configure MCP server filter when specific names are supplied
      ansible.builtin.set_fact:
        mcphost_mcp_servers_filter: "{{ deployment_mcp_servers }}"
        deployment_auto_discover_effective: true
      when: deployment_mcp_servers | length > 0

    - name: Use deployment_auto_discover when no filter is provided
      ansible.builtin.set_fact:
        deployment_auto_discover_effective: "{{ deployment_auto_discover }}"
      when: deployment_mcp_servers | length == 0

  tasks:
    - name: Apply ansible-ollama_mcphost role
      ansible.builtin.import_role:
        name: "{{ role_name | default('ansible-ollama_mcphost') }}"
      vars:
        ollama_state: present
        ollama_model: "{{ deployment_model }}"
        ollama_pull_models:
          - "{{ deployment_model }}"
        ollama_gpu_enabled: "{{ deployment_gpu_enabled }}"
        ollama_gpu_runtime: "{{ deployment_gpu_runtime }}"

        mcphost_state: present
        mcphost_model_provider: "ollama"
        mcphost_model_name: "{{ deployment_model }}"
        mcphost_provider_url: "http://localhost:11434/"
        mcphost_config_path: "{{ lookup('env', 'HOME') }}/.mcphost.yml"
        mcphost_provider_api_key: "{{ deployment_api_key }}"
        mcphost_provider_api_key_env_var: "{{ deployment_api_key_env_var }}"
        mcphost_system_prompt: "{{ deployment_system_prompt }}"
        mcphost_system_prompt_file: "{{ deployment_system_prompt_file }}"
        mcphost_mcp_servers_auto_discover: "{{ deployment_auto_discover_effective }}"
        mcphost_mcp_servers_dirs:
          - "{{ role_files_path }}/mcp_servers"
          - "{{ lookup('env', 'HOME') }}/mcp_servers"

  post_tasks:
    - name: Display deployment summary
      ansible.builtin.debug:
        msg: |
          {%- set summary_ollama_state = (ollama_state | default('present')) -%}
          {%- set summary_mcphost_state = (mcphost_state | default('present')) -%}
          {%- set summary_is_removal = (summary_ollama_state == 'absent' and summary_mcphost_state == 'absent') -%}
          ========================================
          {{ 'Removal Complete!' if summary_is_removal else 'Deployment Complete!' }}
          ========================================

          {%- if summary_is_removal %}
          Removed components:
            - Ollama: {{ 'yes' if summary_ollama_state == 'absent' else 'no' }}
            - mcphost: {{ 'yes' if summary_mcphost_state == 'absent' else 'no' }}
          Data directory purged: {{ 'yes' if ollama_cleanup_data | default(true) else 'no' }}
          Model cleanup enabled: {{ 'yes' if ollama_cleanup_models | default(true) else 'no' }}

          Next steps:
            - Re-run ansible-playbook deploy.yml to redeploy.
          {%- else %}
          Ollama Model: {{ deployment_model }}
          GPU Enabled: {{ deployment_gpu_enabled }} {% if deployment_gpu_enabled %}({{ deployment_gpu_runtime }}){% endif %}
          {% if deployment_auto_discover_effective %}
          MCP Servers: Auto-discovered from:
            - {{ role_files_path }}/mcp_servers
            - ~/mcp_servers
          {% else %}
          MCP Servers: Auto-discovery disabled (only manually defined servers applied)
          {% endif %}
          {% if deployment_mcp_servers | length > 0 %}
          Selected Servers: {{ deployment_mcp_servers | join(', ') }}
          {% elif deployment_auto_discover_effective %}
          Selected Servers: All discovered servers
          {% else %}
          Selected Servers: (none)
          {% endif %}

          To start mcphost:
            mcphost

          Configuration file: {{ lookup('env', 'HOME') }}/.mcphost.yml

          To try different configurations:
            ansible-playbook deploy.yml -e "model=<model>" -e "mcp_servers=['server1','server2']"
          {%- endif %}

          ========================================
