---
# RISU Insights MCP Server deployment
# This example deploys Ollama, mcphost, and automatically configures the RISU Insights MCP server
#
# Prerequisites:
# 1. Clone the risu-insights repository into the mcp_servers directory:
#    cd mcp_servers/
#    git clone https://github.com/Spectro34/risu-insights.git risu-insights
#
# 2. Set up the virtual environment in the risu-insights directory:
#    cd risu-insights/
#    python3 -m venv .venv
#    source .venv/bin/activate
#    pip install -r requirements.txt
#
# Usage:
#   # Option 1: Use the deployment script (recommended)
#   ./deploy.sh --servers risu-insights --enable-gpu --gpu-runtime rocm
#
#   # Option 2: Use this playbook
#   ansible-playbook examples/risu-insights.yml
#
# The role will automatically discover and configure the RISU Insights server
# from mcp_servers/risu-insights/config.yml
#
# See mcp_servers/risu-insights/README.md for detailed setup instructions.

- name: Bootstrap Ollama and MCPHost client with RISU Insights
  hosts: localhost
  become: true
  roles:
    - role: ansible-ollama_mcphost
      # Ollama configuration
      ollama_state: present
      ollama_model: "gpt-oss:20b"
      ollama_pull_models:
        - "gpt-oss:20b"
      ollama_gpu_enabled: true
      ollama_gpu_runtime: "rocm"  # Use "cuda" for NVIDIA GPUs

      # mcphost configuration
      mcphost_state: present
      mcphost_model_provider: "ollama"
      mcphost_model_name: "gpt-oss:20b"
      mcphost_provider_url: "http://localhost:11434/"
      mcphost_config_path: "{{ lookup('env', 'HOME') }}/.mcphost.yml"
      
      # Auto-discovery is enabled by default
      # The role will automatically find and configure MCP servers from:
      # - {{ role_path }}/mcp_servers (this role's mcp_servers directory)
      # - ~/mcp_servers (user's home directory)
      #
      # To disable auto-discovery and use manual configuration:
      # mcphost_mcp_servers_auto_discover: false
      # mcphost_mcp_servers:
      #   - name: "risu-insights"
      #     type: "local"
      #     ...
