---
# RISU Agent MCP helper example
# This example deploys Ollama, mcphost, and auto-configures the bundled
# RISU helper servers that live under
# roles/ansible-ollama_mcphost/mcp_servers/risu-agent/.
#
# Usage:
#   # Deploy everything (RISU helper included)
#   ansible-playbook deploy.yml
#
#   # Or limit to the RISU helper servers
#   ansible-playbook deploy.yml \
#     -e "mcp_servers=['risu-agent-filesystem','risu-agent-bash']"
#
#   # Or run this example playbook directly:
#   ansible-playbook examples/risu-agent.yml
#
# Set RISU_AGENT_ROOT (or edit the files under mcp_servers/risu-agent/) if you
# want the helper to operate on a different RISU checkout.

- name: Bootstrap Ollama and mcphost client with the bundled RISU agent
  hosts: localhost
  become: true
  roles:
    - role: ansible-ollama_mcphost
      # Ollama configuration
      ollama_state: present
      ollama_model: "gpt-oss:20b"
      ollama_pull_models:
        - "gpt-oss:20b"
      ollama_gpu_enabled: true
      ollama_gpu_runtime: "rocm"  # Use "cuda" for NVIDIA GPUs

      # mcphost configuration
      mcphost_state: present
      mcphost_model_provider: "ollama"
      mcphost_model_name: "gpt-oss:20b"
      mcphost_provider_url: "http://localhost:11434/"
      mcphost_config_path: "{{ lookup('env', 'HOME') }}/.mcphost.yml"
      
      # Auto-discovery is enabled by default
      # The role will automatically find and configure MCP servers from:
      # - {{ role_path }}/mcp_servers (this role's mcp_servers directory)
      # - ~/mcp_servers (user's home directory)
      #
      # To disable auto-discovery and use manual configuration:
      # mcphost_mcp_servers_auto_discover: false
      # mcphost_mcp_servers:
      #   - name: "risu-agent-filesystem"
      #     type: "builtin"
      #     name: "fs"
      #     ...
